<includeonly>=</includeonly>==[[Additional features - Direct Integration Manual Index|Additional features]]==<includeonly>=</includeonly>
#	[[Additional features - Direct Integration Manual Index#Use of extra fields|Use of extra fields]]
#	[[Additional features - Direct Integration Manual Index#Code table for extra fields|Code table for extra fields]]
#	[[Additional features - Direct Integration Manual Index#Personalized email|Personalized email]]
#	[[Additional features - Direct Integration Manual Index#GENERATION OF NOTES WITH AND WITHOUT DOCUMENT REFERENCE|GENERATION OF NOTES WITH AND WITHOUT DOCUMENT REFERENCE]]
##	[[Additional features - Direct Integration Manual Index#Credit and debit notes that affect prior validation invoices|Credit and debit notes that affect prior validation invoices]]
##	[[Additional features - Direct Integration Manual Index#Credit and debit notes that do not affect invoices|Credit and debit notes that do not affect invoices]]
##	[[Additional features - Direct Integration Manual Index#TRANSMISSION OF CONTINGENCY DOCUMENTS TYPE 03 (ATTRIBUTABLE TO THE ISSUER)|TRANSMISSION OF CONTINGENCY DOCUMENTS TYPE 03 (ATTRIBUTABLE TO THE ISSUER)]]
#	[[Additional features - Direct Integration Manual Index#Submit electronic documents on reception platforms|Submit electronic documents on reception platforms]]
#	[[Additional features - Direct Integration Manual Index#Standard of the name of XML electronic documents|Standard of the name of XML electronic documents]]
#	[[Additional features - Direct Integration Manual Index#Enablement environment|Enablement environment]]
<includeonly>=</includeonly>==[[Property code tables for document issuance - Direct Integration Manual Index |Property code tables for document issuance]]==<includeonly>=</includeonly>
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 1|Table 1]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 2|Table 2]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 3|Table 3]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 4|Table 4]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 5|Table 5]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 6|Table 6]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 7|Table 7]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 8|Table 8]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 9|Table 9]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 10|Table 10]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 11|Table 11]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 12|Table 12]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 13|Table 13]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 14|Table 14]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 15|Table 15]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 16|Table 16]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 17|Table 17]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 18|Table 18]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 19|Table 19]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 20|Table 20]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 21|Table 21]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 22|Table 22]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 23|Table 23]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 24|Table 24]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 25|Table 25]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 26|Table 26]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 27|Table 27]]
#	[[Property code tables for document issuance - Direct Integration Manual Index #Table 28|Table 28]]
