[[Category:Manuales|I]] 
__NOTOC__

[[File:HKAFactura 3.png|500px|center|HKAFactura]]

<includeonly>=</includeonly>==[[Generalities - Direct Integration Manual Index - Electronic Bill|Generalities]]==<includeonly>=</includeonly>
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#Version record|Version record]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#How to get support?|How to get support?]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#General description|General description]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#What is The Factory HKA-DFACTURE?|What is The Factory HKA-DFACTURE?]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#What is The Factory HKA-Dfactura?|What is The Factory HKA-Dfactura?]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#What is Dintegración?|What is Dintegración?]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#Functionalities|Functionalities]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#The direct integration|The direct integration]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#Technical requirements for direct integration|Technical requirements for direct integration]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#Electronic invoice operation scheme with prior validation|Electronic invoice operation scheme with prior validation]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#What is the electronic invoice with prior validation?|What is the electronic invoice with prior validation?]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#Who participates in this scheme?|Who participates in this scheme?]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#Advantages of Electronic Billing|Advantages of Electronic Billing]]
##	[[Generalities - Direct Integration Manual Index - Electronic Bill#Electronic Billing Process with Prior Validation|Electronic Billing Process with Prior Validation]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#Process characteristics with Prior Validation|Process characteristics with Prior Validation]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#Information security: recommendations on the implementation of electronic invoicing within the issuer's network and systems|Information security: recommendations on the implementation of electronic invoicing within the issuer's network and systems]]
#	[[Generalities - Direct Integration Manual Index - Electronic Bill#Web services soap with prior validation|Web services soap with prior validation]]

<includeonly>=</includeonly>==[[Web Soap Broadcast Service Methods - Direct Integration Manual Index|Web Soap Broadcast Service Methods]]==<includeonly>=</includeonly>
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Enviar Method|Enviar Method]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.FacturaGeneral|Class.FacturaGeneral]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Anticipos|Class.Anticipos]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Autorizado|Class.Autorizado]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.CargosDescuentos|Class.CargosDescuentos]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Cliente|Class.Cliente]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.CondicionPago|Class.CondicionPago]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.FacturaDetalle|Class.FacturaDetalle]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Destinatario|Class.Destinatario]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.DocumentoReferenciado|Class.DocumentoReferenciado]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Entrega|Class.Entrega]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Extras|Class.Extras]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Extensible|Class.Extensible]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.FacturaImpuestos|Class.FacturaImpuestos]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.ImpuestosTotales|Class.ImpuestosTotales]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.MediosDePago|Class.MediosDePago]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.OrdenDeCompra|Class.OrdenDeCompra]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.TasaDeCambio|Class.TasaDeCambio]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.TasaDeCambioAlternativa|Class.TasaDeCambioAlternativa]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.TerminosEntrega|Class.TerminosEntrega]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Direccion|Class.Direccion]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Coordenadas|Class.Coordenadas]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Tributos|Class.Tributos]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.InformacionLegalCliente|Class.InformacionLegalCliente]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Obligaciones|Class.Obligaciones]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.LineaInformacionAdicional|Class.LineaInformacionAdicional]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.DatosTransportistas|Class.DatosTransportistas]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.DocumentoReferencia|Class.DocumentoReferencia]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.sectorSalud|Class.sectorSalud]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.Beneficiario|Class.Beneficiario]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.DatosPacientesSalud|Class.DatosPacientesSalud]]
##	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Class.GeneralSalud|Class.GeneralSalud]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#EstadoDocumento Method|EstadoDocumento Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#Método EnvioCorreo Method|Método EnvioCorreo Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#DescargaPDF Method|DescargaPDF Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#DescargaXML Method|DescargaXML Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#FoliosRestantes Method|FoliosRestantes Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#CargarCertificado Method|CargarCertificado Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#DescargarEventoXML Method|DescargarEventoXML Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#GenerarContenedor Method|GenerarContenedor Method]]
#	[[Web Soap Broadcast Service Methods - Direct Integration Manual Index#GenerarEvento Method|GenerarEvento Method]]
<includeonly>=</includeonly>==[[Métodos servicio adjuntos web soap - Direct Integration Manual Index|Métodos servicio adjuntos web soap]]==<includeonly>=</includeonly>
#[[Métodos servicio adjuntos web soap - Direct Integration Manual Index#Método “CargarAdjuntos”|Método “CargarAdjuntos”]]
#	[[Métodos servicio adjuntos web soap - Direct Integration Manual Index#ESCENARIOS EMISIÓN DE DOCUMENTOS CON REPRESENTACIÓN GRÁFICA|ESCENARIOS EMISIÓN DE DOCUMENTOS CON REPRESENTACIÓN GRÁFICA]]
#	[[Métodos servicio adjuntos web soap - Direct Integration Manual Index#Representación gráfica estándar (Uso del parámetro adjuntos del Enviar method en ‘0’ o ‘1’)|Representación gráfica estándar (Uso del parámetro adjuntos del Enviar method en ‘0’ o ‘1’)]]
#	[[Métodos servicio adjuntos web soap - Direct Integration Manual Index#Representación gráfica personalizada por TFHKA|Representación gráfica personalizada por TFHKA]]
#	[[Métodos servicio adjuntos web soap - Direct Integration Manual Index#Representación gráfica enviada como adjunto desde el sistema administrativo o ERP (Uso del parámetro adjuntos del Enviar method en ‘11’)|Representación gráfica enviada como adjunto desde el sistema administrativo o ERP (Uso del parámetro adjuntos del Enviar method en ‘11’)]]
<includeonly>=</includeonly>==[[Métodos servicio reportes web soap - Direct Integration Manual Index|Métodos servicio reportes web soap]]==<includeonly>=</includeonly>
#	[[Métodos servicio reportes web soap - Direct Integration Manual Index#Método “DescargarReporte”|Método “DescargarReporte”]]
#	[[Métodos servicio reportes web soap - Direct Integration Manual Index#Método “ProgramarReporte”|Método “ProgramarReporte”]]
#	[[Métodos servicio reportes web soap - Direct Integration Manual Index#Método “SolicitudReporteSincrono”|Método “SolicitudReporteSincrono”]]
<includeonly>=</includeonly>==[[Caracteristicas adicionales - Direct Integration Manual Index|Caracteristicas adicionales]]==<includeonly>=</includeonly>
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Uso de campos extras|Uso de campos extras]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Tabla de códigos para campos extras|Tabla de códigos para campos extras]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Correo electrónico personalizado|Correo electrónico personalizado]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#GENERACIÓN DE NOTAS CON Y SIN REFERENCIA A DOCUMENTO|GENERACIÓN DE NOTAS CON Y SIN REFERENCIA A DOCUMENTO]]
##	[[Caracteristicas adicionales - Direct Integration Manual Index#Notas de crédito y débito que afecten a facturas de validación previa|Notas de crédito y débito que afecten a facturas de validación previa]]
##	[[Caracteristicas adicionales - Direct Integration Manual Index#Notas de crédito y débito que no afecten a facturas|Notas de crédito y débito que no afecten a facturas]]
##	[[Caracteristicas adicionales - Direct Integration Manual Index#TRANSMISIÓN DE DOCUMENTOS DE CONTINGENCIA TIPO 03 (ATRIBUIBLE AL EMISOR)|TRANSMISIÓN DE DOCUMENTOS DE CONTINGENCIA TIPO 03 (ATRIBUIBLE AL EMISOR)]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Radicar documentos electrónicos en plataformas de recepción|Radicar documentos electrónicos en plataformas de recepción]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Estándar del nombre de los documentos electrónicos XML|Estándar del nombre de los documentos electrónicos XML]]
#	[[Caracteristicas adicionales - Direct Integration Manual Index#Ambiente de habilitación|Ambiente de habilitación]]
<includeonly>=</includeonly>==[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index|Tablas de códigos de propiedades para emisión de documentos]]==<includeonly>=</includeonly>
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 1|Tabla 1]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 2|Tabla 2]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 3|Tabla 3]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 4|Tabla 4]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 5|Tabla 5]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 6|Tabla 6]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 7|Tabla 7]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 8|Tabla 8]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 9|Tabla 9]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 10|Tabla 10]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 11|Tabla 11]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 12|Tabla 12]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 13|Tabla 13]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 14|Tabla 14]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 15|Tabla 15]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 16|Tabla 16]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 17|Tabla 17]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 18|Tabla 18]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 19|Tabla 19]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 20|Tabla 20]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 21|Tabla 21]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 22|Tabla 22]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 23|Tabla 23]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 24|Tabla 24]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 25|Tabla 25]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 26|Tabla 26]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 27|Tabla 27]]
#	[[Tablas de códigos de propiedades para emisión de documentos - Direct Integration Manual Index#Tabla 28|Tabla 28]]

<includeonly>=</includeonly>==[[Catálogo de errores de respuesta del servicio web - Direct Integration Manual Index|Catálogo de errores de respuesta del servicio web]]==<includeonly>=</includeonly>






{{clear}}
<!--
-->
